[package]
name = "tinypix"
version = "3.5.0"
edition = "2021"
build = "build.rs"

[lib]
name = "tinypix_lib"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "tinypix"
path = "src/main.rs"

[features]
default = ["psd"]
psd = []

[package.metadata.tauri-winres]
FileDescription = "TinyPix Pro"
ProductName = "TinyPix Pro"
OriginalFilename = "TinyPix Pro.exe"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
image = "0.25"
zune-psd = "0.4"
zune-core = "0.4"
rayon = "1.10"
thiserror = "2"
which = "5"
tokio = { version = "1", features = ["process", "io-util", "rt-multi-thread", "time"] }
dirs = "5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
kamadak-exif = "0.6"

uuid = { version = "1", features = ["v4"] }
