import type { Config } from 'tailwindcss'

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── TinyPix 3.5 Pro Design System (Apple Gray) ──
        'surface': '#f5f5f7',
        'surface-dim': '#e5e5ea',
        'surface-bright': '#f5f5f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f2f7',
        'surface-container': '#e5e5ea',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e5e5ea',
        'surface-variant': '#e5e5ea',
        'on-surface': '#1d1d1f',
        'on-surface-variant': '#6e6e73',
        'outline': '#7e7576',
        'outline-variant': '#d1d1d6',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'secondary': '#4b6700',
        'on-secondary': '#ffffff',
        'secondary-container': '#b4f400',
        'on-secondary-container': '#4b6700',
        'secondary-fixed': '#b4f700',
        'secondary-fixed-dim': '#a0d800',
        'on-secondary-fixed': '#141f00',
        'on-secondary-fixed-variant': '#374e00',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f5f5f7',
        'on-background': '#1d1d1f',
        'surface-tint': '#5e5e5e',
        // Legacy colors (keep for compatibility)
        canvas: '#F6F4F0',
        'surface-hover': '#F0EDE6',
        'surface-active': '#FBF3E8',
        'primary-hover': '#9C6028',
        'primary-active': '#7A4A1F',
        border: '#D6D3CD',
        ink: '#1C1A16',
        'ink-secondary': '#4A4741',
        muted: '#A49E92',
        'control-bg': '#E4E1DA',
        'pro-bg': '#f5f5f7',
        'pro-canvas': '#1E1E1E',
        'pro-surface': '#f2f2f7',
        'pro-surface-2': '#e9e8e7',
        'pro-green': '#b4f700',
        'pro-green-2': '#a0d800',
        'pro-green-dark': '#4b6700',
        'pro-green-dim': '#e5e5ea',
        'pro-ink': '#1d1d1f',
        'pro-muted': '#6e6e73',
        'pro-muted-2': '#9ca3af',
        'pro-border': '#d1d1d6',
        'pro-border-2': '#e5e4e3',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'display-lg': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'headline-md': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'body-lg': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'body-sm': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'label-caps': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Segoe UI Variable"', '"Segoe UI"', '"Microsoft YaHei UI"', '"PingFang SC"', 'system-ui', 'sans-serif'],
        'mono-status': ['"SF Mono"', 'Menlo', 'Consolas', 'Monaco', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-status': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'container-padding': '32px',
        'card-gap': '24px',
        'control-stack': '12px',
        'margin-sm': '16px',
        'margin-lg': '48px',
      }
    }
  },
  plugins: []
} satisfies Config
